import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { ref } from 'vue'
import UserVpnView from '../user/VpnView.vue'
import AdminVpnView from '../admin/VpnView.vue'
import VpnSubscriptionDetails from '@/components/vpn/VpnSubscriptionDetails.vue'
import type { VpnEgress, VpnSubscription } from '@/api/vpn'
import { GIB, gibToBytes, vpnIsAvailable } from '@/utils/vpn'

const mocks = vi.hoisted(() => ({
  get: vi.fn(), create: vi.fn(), refresh: vi.fn(), servers: vi.fn(), summary: vi.fn(), subscriptions: vi.fn(),
  saveServer: vi.fn(), probe: vi.fn(), adminCreate: vi.fn(), update: vi.fn(), action: vi.fn(), delete: vi.fn(),
  groups: vi.fn(), createGroup: vi.fn(), updateGroup: vi.fn(), setUserGroup: vi.fn(),
  ensureEgress: vi.fn(),
  listUsers: vi.fn(), copy: vi.fn(), success: vi.fn()
}))
vi.mock('@/api/vpn', () => ({
  vpnAPI: { get: mocks.get, create: mocks.create, refresh: mocks.refresh },
  adminVpnAPI: { servers: mocks.servers, summary: mocks.summary, subscriptions: mocks.subscriptions, saveServer: mocks.saveServer, probe: mocks.probe, create: mocks.adminCreate, update: mocks.update, action: mocks.action, delete: mocks.delete, groups: mocks.groups, createGroup: mocks.createGroup, updateGroup: mocks.updateGroup, setUserGroup: mocks.setUserGroup, ensureEgress: mocks.ensureEgress }
}))
vi.mock('@/api/admin/users', () => ({ list: mocks.listUsers, default: { list: mocks.listUsers } }))
vi.mock('@/components/layout/AppLayout.vue', () => ({ default: { template: '<div><slot /></div>' } }))
vi.mock('@/composables/useClipboard', () => ({ useClipboard: () => ({ copyToClipboard: mocks.copy }) }))
vi.mock('@/stores/app', () => ({ useAppStore: () => ({ showSuccess: mocks.success }) }))
vi.mock('vue-i18n', async () => ({
  ...await vi.importActual<typeof import('vue-i18n')>('vue-i18n'),
  useI18n: () => ({ t: (key: string, params?: Record<string, unknown>) => key === 'vpn.policy' ? `${key}:${params?.quota}` : key, te: (key: string) => key.startsWith('vpn.states.') || key === 'vpn.reasons.balance_required', locale: ref('zh') })
}))

const subscription = (overrides: Partial<VpnSubscription> = {}): VpnSubscription => ({
  id: 8, user_id: 17, user_email: 'person@example.com', server_id: 3, server_name: 'Node', remote_username: 'pc_sample',
  group_id: 1, group_name: '默认组', group_quota_bytes: 80 * GIB,
  status: 'active', apply_status: 'applied', access_state: 'allowed', quota_bytes: 30 * GIB, upload_bytes: GIB,
  download_bytes: 2 * GIB, used_bytes: 3 * GIB, remaining_bytes: 27 * GIB, period_start: '2026-08-21T16:00:00Z',
  period_end: '2026-09-21T16:00:00Z', next_reset_at: '2026-09-21T16:00:00Z', sampled_at: '2026-09-20T01:00:00Z',
  synced_at: '2026-09-20T01:00:01Z', accounting_status: 'ok', last_error: '', operation_status: 'succeeded',
  created_at: '2026-09-01T00:00:00Z', subscription_urls: { clash: 'https://vpn.example/sub/secret/clash-meta', base64: 'https://vpn.example/sub/secret/v2ray' }, ...overrides
})
const server = { id: 3, name: 'Node', base_url: 'https://vpn.example', admin_username: 'integration', enabled: true, healthy: true, health_error: '', personal_user_count: 2, assigned_count: 1, pending_count: 0, last_checked_at: null, created_at: '' }
const egress = (overrides: Partial<VpnEgress> = {}): VpnEgress => ({
  username: 'ops_test', status: 'active', apply_status: 'applied', access_state: 'allowed', unlimited: true,
  subscription_urls: { clash: 'https://vpn.example/sub/ops-secret/clash', base64: 'https://vpn.example/sub/ops-secret/base64', singbox: 'https://vpn.example/sub/ops-secret/singbox' }, ...overrides
})
function deferred<T>() {
  let resolve!: (value: T) => void
  let reject!: (error: unknown) => void
  const promise = new Promise<T>((onResolve, onReject) => { resolve = onResolve; reject = onReject })
  return { promise, resolve, reject }
}
const group = { id: 1, name: '默认组', quota_bytes: 80 * GIB, is_default: true, member_count: 4, subscription_count: 1, pending_count: 0, failed_count: 0 }
const wrappers: VueWrapper[] = []
function view(component: typeof UserVpnView | typeof AdminVpnView) {
  const wrapper = mount(component, { global: { stubs: {
    AppLayout: { template: '<div><slot /></div>' },
    VpnTrafficChart: true,
    BaseDialog: { props: ['show', 'title'], template: '<section v-if="show" role="dialog"><h2>{{ title }}</h2><slot /><slot name="footer" /></section>' }
  } } })
  wrappers.push(wrapper)
  return wrapper
}
function button(wrapper: VueWrapper, label: string) {
  const match = wrapper.findAll('button').find(item => item.text() === label)
  if (!match) throw new Error(`Missing button: ${label}`)
  return match
}
beforeEach(() => {
  vi.clearAllMocks()
  mocks.get.mockResolvedValue({ subscription: null, can_create: true, ineligible_reason: '', default_quota_bytes: 30 * GIB })
  mocks.servers.mockResolvedValue([server])
  mocks.groups.mockResolvedValue([group, { ...group, id: 2, name: '大流量组', quota_bytes: 120 * GIB, is_default: false }])
  mocks.createGroup.mockResolvedValue({ ...group, id: 3, is_default: false })
  mocks.updateGroup.mockResolvedValue(group)
  mocks.setUserGroup.mockResolvedValue({ user_id: 17, group_id: 2, group_name: '大流量组', quota_bytes: 120 * GIB })
  mocks.summary.mockResolvedValue({ total: 1, active: 1, disabled: 0, limited: 0, pending: 0, failed: 0, used_bytes: 3 * GIB, quota_bytes: 30 * GIB, healthy_servers: 1, total_servers: 1 })
  mocks.subscriptions.mockResolvedValue({ items: [subscription()], total: 1, page: 1, page_size: 20 })
  mocks.listUsers.mockResolvedValue({ items: [{ id: 17, email: 'person@example.com' }] })
  mocks.update.mockResolvedValue(subscription())
  mocks.action.mockResolvedValue(subscription())
  mocks.adminCreate.mockResolvedValue(subscription())
  mocks.ensureEgress.mockResolvedValue(egress())
})
afterEach(() => { wrappers.splice(0).forEach(wrapper => wrapper.unmount()); vi.useRealTimers() })

describe('VPN quota and availability', () => {
  it('converts GiB without allowing zero, negative, nonfinite or unsafe quotas', () => {
    expect(gibToBytes(30)).toBe(32212254720)
    expect(gibToBytes(1.5)).toBe(1610612736)
    for (const value of [0, -1, NaN, Infinity, Number.MAX_SAFE_INTEGER]) expect(gibToBytes(value)).toBeNull()
  })
  it('requires an applied, active and permitted subscription before declaring it usable', () => {
    expect(vpnIsAvailable(subscription())).toBe(true)
    expect(vpnIsAvailable(subscription({ apply_status: 'pending' }))).toBe(false)
    expect(vpnIsAvailable(subscription({ access_state: 'unknown' }))).toBe(false)
    expect(vpnIsAvailable(subscription({ status: 'limited' }))).toBe(false)
  })
  it('hides URLs during pending application and exposes real directional usage and sample warnings', () => {
    const wrapper = mount(VpnSubscriptionDetails, { props: { subscription: subscription({ apply_status: 'pending', accounting_status: 'gap_detected' }) } })
    wrappers.push(wrapper)
    expect(wrapper.findAll('input')).toHaveLength(0)
    expect(wrapper.text()).toContain('vpn.staleNotice')
    expect(wrapper.text()).toContain('1.00 GiB')
    expect(wrapper.text()).toContain('2.00 GiB')
    expect(wrapper.text()).not.toContain('vpn.ready')
  })
  it('copies the selected format without putting the credential into a navigation link', async () => {
    const s = subscription()
    const wrapper = mount(VpnSubscriptionDetails, { props: { subscription: s } })
    wrappers.push(wrapper)
    await wrapper.findAll('button')[1].trigger('click')
    expect(mocks.copy).toHaveBeenCalledWith(s.subscription_urls!.base64)
    expect(wrapper.findAll('a')).toHaveLength(0)
    expect(wrapper.find('input').attributes('type')).toBe('password')
  })
})

describe('VPN user flow', () => {
  it('uses the current default quota from the API without changing an existing subscription quota', async () => {
    mocks.get.mockResolvedValue({ subscription: subscription(), can_create: false, ineligible_reason: '', default_quota_bytes: 80 * GIB })
    const wrapper = view(UserVpnView)
    await flushPromises()
    expect(wrapper.text()).toContain('vpn.policy:80.00 GiB')
    expect(wrapper.text()).toContain('30.00 GiB')
    mocks.refresh.mockResolvedValue({ subscription: subscription(), can_create: false, ineligible_reason: '', default_quota_bytes: 96 * GIB })
    await button(wrapper, 'vpn.refresh').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('vpn.policy:96.00 GiB')
    expect(wrapper.text()).toContain('30.00 GiB')
  })
  it('translates the balance eligibility reason returned by the backend', async () => {
    mocks.get.mockResolvedValue({ subscription: null, can_create: false, ineligible_reason: 'balance_required', default_quota_bytes: 30 * GIB })
    const wrapper = view(UserVpnView)
    await flushPromises()
    expect(wrapper.text()).toContain('vpn.reasons.balance_required')
  })
  it('blocks creation when the server reports ineligibility', async () => {
    mocks.get.mockResolvedValue({ subscription: null, can_create: false, ineligible_reason: '余额不足', default_quota_bytes: 30 * GIB })
    const wrapper = view(UserVpnView)
    await flushPromises()
    expect(wrapper.text()).toContain('余额不足')
    expect(button(wrapper, 'vpn.create').attributes('disabled')).toBeDefined()
    expect(mocks.create).not.toHaveBeenCalled()
  })
  it('creates once and polls GET until applied without consuming manual refresh calls', async () => {
    vi.useFakeTimers()
    mocks.create.mockResolvedValue(subscription({ status: 'provisioning', apply_status: 'pending', operation_status: 'pending', access_state: 'unknown', subscription_urls: null }))
    const wrapper = view(UserVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.create').trigger('click')
    await flushPromises()
    expect(mocks.create).toHaveBeenCalledOnce()
    expect(wrapper.text()).toContain('vpn.pendingNotice')
    expect(wrapper.findAll('button').some(item => item.text() === 'vpn.create')).toBe(false)
    mocks.get.mockResolvedValue({ subscription: subscription(), can_create: false, ineligible_reason: '', default_quota_bytes: 30 * GIB })
    await vi.advanceTimersByTimeAsync(5000)
    await flushPromises()
    expect(wrapper.text()).toContain('vpn.ready')
    expect(mocks.refresh).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(10000)
    expect(mocks.get).toHaveBeenCalledTimes(2)
  })
  it('keeps the existing subscription visible when refresh fails', async () => {
    mocks.get.mockResolvedValue({ subscription: subscription(), can_create: false, ineligible_reason: '', default_quota_bytes: 30 * GIB })
    mocks.refresh.mockRejectedValue({ message: '稍后再试', status: 429 })
    const wrapper = view(UserVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.refresh').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('稍后再试')
    expect(wrapper.text()).toContain('30.00 GiB')
  })
})

describe('VPN group administration', () => {
  it('creates a group using GiB converted to bytes', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.addGroup').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    await dialog.find('input:not([type])').setValue('研究组')
    await dialog.find('input[type="number"]').setValue(160.5)
    await dialog.find('form').trigger('submit')
    await flushPromises()
    expect(mocks.createGroup).toHaveBeenCalledWith({ name: '研究组', quota_bytes: 160.5 * GIB })
  })
  it('requires confirmation before applying a group quota to existing subscriptions', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await wrapper.find('[data-group-id="1"] button').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    await dialog.find('input[type="number"]').setValue(100)
    await dialog.find('form').trigger('submit')
    expect(mocks.updateGroup).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('vpn.groupQuotaConfirm')
    await button(wrapper, 'vpn.confirmGroupQuota').trigger('click')
    await flushPromises()
    expect(mocks.updateGroup).toHaveBeenCalledWith(1, { name: '默认组', quota_bytes: 100 * GIB })
    expect(mocks.update).not.toHaveBeenCalled()
    expect(wrapper.findAll('[role="dialog"]')).toHaveLength(0)
  })
  it('renames a group without applying its quota again', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await wrapper.find('[data-group-id="1"] button').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    await dialog.find('input:not([type])').setValue('基础组')
    await dialog.find('form').trigger('submit')
    await flushPromises()
    expect(mocks.updateGroup).toHaveBeenCalledWith(1, { name: '基础组' })
    expect(wrapper.text()).not.toContain('vpn.groupQuotaConfirm')
  })
  it('retains bulk update errors for a retry after confirmation', async () => {
    mocks.updateGroup.mockRejectedValueOnce({ message: '保存失败' })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await wrapper.find('[data-group-id="1"] button').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    await dialog.find('input[type="number"]').setValue(100)
    await dialog.find('form').trigger('submit')
    await button(wrapper, 'vpn.confirmGroupQuota').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('保存失败')
    await button(wrapper, 'vpn.confirmGroupQuota').trigger('click')
    await flushPromises()
    expect(mocks.updateGroup).toHaveBeenCalledTimes(2)
  })
  it('polls group synchronization counts even if no subscription is on the current page', async () => {
    vi.useFakeTimers()
    mocks.groups.mockResolvedValue([{ ...group, pending_count: 1, failed_count: 1 }])
    mocks.subscriptions.mockResolvedValue({ items: [], total: 0 })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    expect(wrapper.text()).toContain('vpn.groupRetryHint')
    mocks.groups.mockResolvedValue([group])
    await vi.advanceTimersByTimeAsync(5000)
    await flushPromises()
    expect(mocks.groups).toHaveBeenCalledTimes(2)
    expect(wrapper.text()).not.toContain('vpn.groupRetryHint')
    await vi.advanceTimersByTimeAsync(10000)
    expect(mocks.groups).toHaveBeenCalledTimes(2)
  })
  it('confirms the target group and applies it without resetting current usage', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    await wrapper.find('[role="dialog"] select').setValue(2)
    await button(wrapper, 'vpn.switchGroup').trigger('click')
    expect(mocks.setUserGroup).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('vpn.switchGroupConfirm')
    mocks.subscriptions.mockResolvedValue({ items: [subscription({ group_id: 2, group_name: '大流量组', group_quota_bytes: 120 * GIB, quota_bytes: 120 * GIB, apply_status: 'pending', operation_status: 'pending' })], total: 1 })
    await button(wrapper, 'vpn.confirmSwitchGroup').trigger('click')
    await flushPromises()
    expect(mocks.setUserGroup).toHaveBeenCalledWith(17, 2)
    expect(wrapper.find('[role="dialog"]').text()).toContain('3.00 GiB')
    expect(wrapper.find('[role="dialog"]').text()).toContain('120.00 GiB')
    expect(button(wrapper, 'vpn.switchGroup').attributes('disabled')).toBeDefined()
  })
  it('blocks group switching for a deletion and does not send an unsafe quota', async () => {
    mocks.subscriptions.mockResolvedValue({ items: [subscription({ status: 'deleting', delete_requested_at: '2026-09-22T00:00:00Z', apply_status: 'failed', operation_status: 'failed' })], total: 1 })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    expect(wrapper.find('[role="dialog"] select').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'vpn.switchGroup').attributes('disabled')).toBeDefined()
    await button(wrapper, 'vpn.addGroup').trigger('click')
    const dialog = wrapper.findAll('[role="dialog"]').at(-1)!
    await dialog.find('input:not([type])').setValue('测试组')
    await dialog.find('input[type="number"]').setValue(Number.MAX_SAFE_INTEGER)
    await dialog.find('form').trigger('submit')
    expect(wrapper.text()).toContain('vpn.invalidQuota')
    expect(mocks.createGroup).not.toHaveBeenCalled()
  })
})

describe('VPN operations subscription', () => {
  it('retrieves and copies every format from a disabled node without changing personal subscriptions', async () => {
    mocks.servers.mockResolvedValue([{ ...server, enabled: false }])
    const wrapper = view(AdminVpnView)
    await flushPromises()
    expect(button(wrapper, 'vpn.egressSubscription').attributes('disabled')).toBeUndefined()
    await button(wrapper, 'vpn.egressSubscription').trigger('click')
    await flushPromises()
    const dialog = wrapper.find('[data-testid="vpn-egress"]')
    expect(mocks.ensureEgress).toHaveBeenCalledWith(3)
    expect(dialog.text()).toContain('Node')
    expect(dialog.text()).toContain('vpn.unlimitedTraffic')
    expect(dialog.text()).toContain('vpn.noExpiry')
    expect(dialog.text()).toContain('vpn.states.applied')
    expect(dialog.text()).toContain('vpn.states.allowed')
    expect(dialog.html()).not.toContain('ops-secret')
    const copyButtons = dialog.findAll('button')
    expect(copyButtons).toHaveLength(3)
    for (const copyButton of copyButtons) await copyButton.trigger('click')
    expect(mocks.copy.mock.calls).toEqual(Object.values(egress().subscription_urls!).map(url => [url]))
    expect(mocks.success).not.toHaveBeenCalled()
    expect(mocks.action).not.toHaveBeenCalled()
    expect(mocks.probe).not.toHaveBeenCalled()
    expect(mocks.update).not.toHaveBeenCalled()
  })
  it('withholds returned URLs while pending and refreshes the same node with an idempotent request', async () => {
    mocks.ensureEgress.mockResolvedValueOnce(egress({ apply_status: 'pending' }))
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.egressSubscription').trigger('click')
    await flushPromises()
    expect(wrapper.find('[data-testid="vpn-egress"]').text()).toContain('vpn.egressPending')
    expect(wrapper.find('[data-testid="vpn-egress"]').findAll('button')).toHaveLength(0)
    await wrapper.find('[role="dialog"]').findAll('button').find(item => item.text() === 'vpn.refresh')!.trigger('click')
    await flushPromises()
    expect(mocks.ensureEgress.mock.calls).toEqual([[3], [3]])
    expect(wrapper.find('[data-testid="vpn-egress"]').findAll('button')).toHaveLength(3)
  })
  it.each([
    { access_state: 'blocked' },
    { subscription_urls: null }
  ])('withholds copy actions until access and URLs are both ready: %j', async overrides => {
    mocks.ensureEgress.mockResolvedValue(egress(overrides))
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.egressSubscription').trigger('click')
    await flushPromises()
    expect(wrapper.find('[data-testid="vpn-egress"]').findAll('button')).toHaveLength(0)
    expect(mocks.copy).not.toHaveBeenCalled()
  })
  it('shows safe failure messages and allows retry without exposing remote credentials', async () => {
    mocks.ensureEgress.mockResolvedValueOnce(egress({ apply_status: 'failed' }))
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.egressSubscription').trigger('click')
    await flushPromises()
    expect(wrapper.find('[role="alert"]').text()).toBe('vpn.egressFailed')
    expect(wrapper.find('[data-testid="vpn-egress"]').findAll('button')).toHaveLength(0)
    mocks.ensureEgress.mockRejectedValueOnce({ message: 'https://vpn.example/sub/private-token' })
    await wrapper.find('[role="dialog"]').findAll('button').find(item => item.text() === 'vpn.refresh')!.trigger('click')
    await flushPromises()
    expect(wrapper.find('[role="alert"]').text()).toBe('vpn.egressLoadFailed')
    expect(wrapper.html()).not.toContain('private-token')
    expect(mocks.success).not.toHaveBeenCalled()
    await wrapper.find('[role="dialog"]').findAll('button').find(item => item.text() === 'vpn.refresh')!.trigger('click')
    await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(wrapper.find('[data-testid="vpn-egress"]').findAll('button')).toHaveLength(3)
  })
  it.each(['resolve', 'reject'] as const)('ignores late %s results after switching or closing dialogs', async outcome => {
    const first = deferred<VpnEgress>()
    const second = deferred<VpnEgress>()
    mocks.servers.mockResolvedValue([server, { ...server, id: 4, name: 'Second node' }])
    mocks.ensureEgress.mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise)
    const wrapper = view(AdminVpnView)
    await flushPromises()
    const openButtons = wrapper.findAll('button').filter(item => item.text() === 'vpn.egressSubscription')
    await openButtons[0].trigger('click')
    await openButtons[1].trigger('click')
    if (outcome === 'resolve') first.resolve(egress())
    else first.reject({ message: 'old private-token' })
    await flushPromises()
    const dialog = wrapper.find('[role="dialog"]')
    expect(dialog.text()).toContain('Second node')
    expect(dialog.text()).toContain('vpn.loading')
    expect(dialog.find('[role="alert"]').exists()).toBe(false)
    expect(dialog.findAll('button').find(item => item.text() === 'vpn.refresh')!.attributes('disabled')).toBeDefined()
    expect(wrapper.find('[data-testid="vpn-egress"]').findAll('button')).toHaveLength(0)
    await button(wrapper, 'common.close').trigger('click')
    second.resolve(egress())
    await flushPromises()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    expect(mocks.ensureEgress.mock.calls).toEqual([[3], [4]])
  })
  it('ignores an old result after reopening the same node', async () => {
    const oldRequest = deferred<VpnEgress>()
    mocks.ensureEgress.mockReturnValueOnce(oldRequest.promise).mockResolvedValueOnce(egress({ apply_status: 'pending' }))
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.egressSubscription').trigger('click')
    await button(wrapper, 'common.close').trigger('click')
    await button(wrapper, 'vpn.egressSubscription').trigger('click')
    await flushPromises()
    oldRequest.resolve(egress())
    await flushPromises()
    expect(wrapper.find('[data-testid="vpn-egress"]').text()).toContain('vpn.egressPending')
    expect(wrapper.find('[data-testid="vpn-egress"]').findAll('button')).toHaveLength(0)
  })
})

describe('VPN administrator flow', () => {
  it('keeps a deletion visible until the archived result confirms success', async () => {
    vi.useFakeTimers()
    const deleting = subscription({ status: 'deleting', apply_status: 'pending', operation_status: 'pending', delete_requested_at: '2026-09-22T00:00:00Z' })
    mocks.delete.mockResolvedValue(deleting)
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    await button(wrapper, 'vpn.deleteSubscription').trigger('click')
    expect(mocks.delete).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('vpn.deleteConfirm')
    mocks.subscriptions.mockResolvedValue({ items: [deleting], total: 1 })
    await button(wrapper, 'vpn.confirmDelete').trigger('click')
    await flushPromises()
    expect(mocks.delete).toHaveBeenCalledWith(8)
    expect(wrapper.find('tbody').text()).toContain('person@example.com')
    expect(button(wrapper, 'vpn.edit').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'vpn.revoke').attributes('disabled')).toBeDefined()
    mocks.subscriptions.mockImplementation(async params => params.status === 'deleted'
      ? { items: [subscription({ status: 'deleted', deleted_at: '2026-09-22T00:00:05Z' })], total: 1 }
      : { items: [], total: 0 })
    await vi.advanceTimersByTimeAsync(5000)
    await flushPromises()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    expect(wrapper.text()).toContain('vpn.noResults')
    expect(mocks.success).toHaveBeenCalledWith('vpn.deletedSuccess')
  })
  it('retains deletion errors and allows the administrator to retry', async () => {
    mocks.delete.mockRejectedValueOnce({ message: '节点暂不可用' }).mockResolvedValueOnce(subscription({ status: 'deleting', apply_status: 'pending' }))
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    await button(wrapper, 'vpn.deleteSubscription').trigger('click')
    await button(wrapper, 'vpn.confirmDelete').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('节点暂不可用')
    await button(wrapper, 'vpn.confirmDelete').trigger('click')
    await flushPromises()
    expect(mocks.delete).toHaveBeenCalledTimes(2)
  })
  it('keeps failed deletion read-only while allowing retry', async () => {
    mocks.subscriptions.mockResolvedValue({ items: [subscription({ status: 'deleting', apply_status: 'failed', operation_status: 'failed', delete_requested_at: '2026-09-22T00:00:00Z' })], total: 1 })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    expect(button(wrapper, 'vpn.edit').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'vpn.revoke').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'vpn.retry').attributes('disabled')).toBeUndefined()
    expect(button(wrapper, 'vpn.deleteSubscription').attributes('disabled')).toBeUndefined()
  })
  it('saves node quota and current usage adjustment in bytes, including zero', async () => {
    mocks.servers.mockResolvedValue([{ ...server, traffic_quota_bytes: 1024 * GIB, traffic_used_offset_bytes: 5 * GIB, traffic_period_start: '2026-09-21T16:00:00Z', traffic_offset_period_start: '2026-09-21T16:00:00Z' }])
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.editServer').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    const fields = dialog.findAll('input[type="number"]')
    await fields[0].setValue(2048)
    await fields[1].setValue(0)
    await dialog.find('form').trigger('submit')
    await flushPromises()
    expect(mocks.saveServer).toHaveBeenCalledWith(expect.objectContaining({ traffic_quota_bytes: 2048 * GIB, traffic_used_offset_bytes: 0 }), 3)
  })
  it('does not reapply an expired usage adjustment during an unrelated server edit', async () => {
    mocks.servers.mockResolvedValue([{ ...server, traffic_quota_bytes: 1024 * GIB, traffic_used_offset_bytes: 5 * GIB, traffic_period_start: '2026-09-21T16:00:00Z', traffic_offset_period_start: '2026-08-21T16:00:00Z' }])
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.editServer').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    expect((dialog.findAll('input[type="number"]')[1].element as HTMLInputElement).value).toBe('0')
    await dialog.find('form').trigger('submit')
    await flushPromises()
    expect(mocks.saveServer.mock.calls[0][0]).not.toHaveProperty('traffic_used_offset_bytes')
  })
  it('does not present unknown or expired node telemetry as a full remaining quota', async () => {
    mocks.servers.mockResolvedValue([{ ...server, traffic_quota_bytes: 1024 * GIB, traffic_remaining_bytes: 1024 * GIB, traffic_accounting_status: 'ok', traffic_sampled_at: '2026-01-01T00:00:00Z', traffic_period_end: '2026-02-01T00:00:00Z' }])
    const wrapper = view(AdminVpnView)
    await flushPromises()
    const node = wrapper.find('article')
    const remaining = node.findAll('dl > div').find(item => item.text().startsWith('vpn.remaining'))!
    expect(remaining.find('dd').text()).toBe('—')
    expect(node.text()).toContain('vpn.staleNotice')
  })
  it('marks fresh partial history as an estimate and shows when coverage began', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-09-22T01:00:00Z'))
    mocks.servers.mockResolvedValue([{ ...server, traffic_quota_bytes: 1024 * GIB, traffic_used_bytes: 24 * GIB, traffic_remaining_bytes: 1000 * GIB, traffic_accounting_status: 'partial_history', traffic_sampled_at: '2026-09-22T01:00:00Z', traffic_period_end: '2026-10-21T16:00:00Z', traffic_available_from: '2026-09-22T00:00:00Z' }])
    const wrapper = view(AdminVpnView)
    await flushPromises()
    const node = wrapper.find('article')
    const remaining = node.findAll('dl > div').find(item => item.text().startsWith('vpn.remaining'))!
    expect(remaining.text()).toContain('1000.00 GiB')
    expect(remaining.text()).toContain('vpn.estimated')
    expect(node.text()).not.toContain('vpn.nodeTrafficHint')
    expect(node.text()).not.toContain('vpn.nodePartialHistory')
    expect(remaining.classes()).toContain('bg-primary-50')
    expect(node.findAll('dl > div').find(item => item.text().startsWith('vpn.used'))!.classes()).toContain('bg-gray-50')
    const coverage = node.findAll('dl > div').find(item => item.text().startsWith('vpn.availableFrom'))!
    expect(coverage.find('dd').text()).toContain('2026')
    expect(coverage.find('dd').text()).not.toBe('—')
  })
  it.each([{ accounting: 'stale', used: GIB }, { accounting: 'gap_detected', used: GIB }, { accounting: 'unavailable', used: GIB }, { accounting: 'partial_history', used: null }])('does not show remaining traffic for invalid $accounting telemetry', async ({ accounting, used }) => {
    mocks.servers.mockResolvedValue([{ ...server, traffic_quota_bytes: 1024 * GIB, traffic_used_bytes: used, traffic_remaining_bytes: 1024 * GIB, traffic_accounting_status: accounting, traffic_sampled_at: '2026-09-22T01:00:00Z', traffic_period_end: '2099-10-21T16:00:00Z' }])
    const wrapper = view(AdminVpnView)
    await flushPromises()
    const fields = wrapper.find('article').findAll('dl > div')
    expect(fields.find(item => item.text().startsWith('vpn.remaining'))!.find('dd').text()).toBe('—')
    expect(fields.find(item => item.text().startsWith('vpn.used'))!.find('dd').text()).toBe(used === null ? '—' : '1.00 GiB')
  })
  it('preserves credentials and locks the address for a bound node', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.editServer').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    expect(dialog.find('input[type="url"]').attributes('disabled')).toBeDefined()
    expect((dialog.find('input[type="password"]').element as HTMLInputElement).value).toBe('')
    await dialog.find('form').trigger('submit')
    await flushPromises()
    expect(mocks.saveServer).toHaveBeenCalledWith({ name: 'Node', base_url: 'https://vpn.example', admin_username: 'integration', admin_password: '', enabled: true }, 3)
  })
  it('rejects a non-HTTPS management URL without sending credentials', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.addServer').trigger('click')
    const dialog = wrapper.find('[role="dialog"]')
    await dialog.find('input[type="url"]').setValue('http://vpn.example')
    await dialog.find('form').trigger('submit')
    expect(mocks.saveServer).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('vpn.invalidHttps')
  })
  it('searches existing users and activates for the selected user', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.createForUser').trigger('click')
    await flushPromises()
    const dialog = wrapper.find('[role="dialog"]')
    await dialog.find('select').setValue(17)
    await dialog.findAll('button').find(item => item.text() === 'vpn.createForUser')!.trigger('click')
    await flushPromises()
    expect(mocks.adminCreate).toHaveBeenCalledWith(17)
    expect(mocks.listUsers).toHaveBeenCalledWith(1, 50, { search: '', status: 'active' })
  })
  it('updates quota in bytes and supports disabling the same subscription', async () => {
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    await button(wrapper, 'vpn.edit').trigger('click')
    const dialog = wrapper.findAll('[role="dialog"]').at(-1)!
    await dialog.find('input[type="number"]').setValue(45.5)
    await dialog.find('input[type="checkbox"]').setValue(false)
    await dialog.find('form').trigger('submit')
    await flushPromises()
    expect(mocks.update).toHaveBeenCalledWith(8, { quota_bytes: 45.5 * GIB, enabled: false })
  })
  it('requires explicit confirmation to rotate credentials and preserves errors', async () => {
    mocks.action.mockRejectedValue({ status: 409, message: '操作处理中' })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    await button(wrapper, 'vpn.revoke').trigger('click')
    expect(mocks.action).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('vpn.revokeConfirm')
    await button(wrapper, 'vpn.confirm').trigger('click')
    await flushPromises()
    expect(mocks.action).toHaveBeenCalledWith(8, 'revoke')
    expect(wrapper.text()).toContain('操作处理中')
  })
  it('explains migration before rotating a subscription on its disabled source node', async () => {
    mocks.servers.mockResolvedValue([{ ...server, id: 4, name: 'Destination' }, { ...server, enabled: false }])
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    await button(wrapper, 'vpn.revoke').trigger('click')
    expect(wrapper.text()).toContain('vpn.revokeMigrateConfirm')
    expect(wrapper.text()).not.toContain('vpn.revokeConfirm')
    expect(mocks.action).not.toHaveBeenCalled()
    await button(wrapper, 'vpn.confirm').trigger('click')
    await flushPromises()
    expect(mocks.action).toHaveBeenCalledWith(8, 'revoke')
  })
  it('retries an existing failed operation while preventing creation of a second account', async () => {
    mocks.subscriptions.mockResolvedValue({ items: [subscription({ apply_status: 'failed', operation_status: 'failed', status: 'provisioning' })], total: 1 })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    await button(wrapper, 'vpn.retry').trigger('click')
    await flushPromises()
    expect(mocks.action).toHaveBeenCalledWith(8, 'retry')
    expect(mocks.adminCreate).not.toHaveBeenCalled()
  })
  it('disables quota editing and rotation while another operation is pending', async () => {
    mocks.subscriptions.mockResolvedValue({ items: [subscription({ apply_status: 'pending', operation_status: 'pending' })], total: 1 })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    expect(button(wrapper, 'vpn.edit').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'vpn.revoke').attributes('disabled')).toBeDefined()
  })
  it('continues refreshing open details after an applied subscription leaves the filtered list', async () => {
    vi.useFakeTimers()
    mocks.subscriptions.mockResolvedValue({ items: [subscription({ apply_status: 'pending', operation_status: 'running' })], total: 1 })
    const wrapper = view(AdminVpnView)
    await flushPromises()
    await button(wrapper, 'vpn.details').trigger('click')
    mocks.subscriptions.mockResolvedValueOnce({ items: [], total: 0 }).mockResolvedValueOnce({ items: [subscription()], total: 1 })
    await vi.advanceTimersByTimeAsync(5000)
    await flushPromises()
    expect(mocks.subscriptions).toHaveBeenLastCalledWith({ page: 1, page_size: 20, q: 'pc_sample' })
    expect(wrapper.find('[role="dialog"]').text()).toContain('vpn.ready')
  })
})
